MANE.GRCh38.v1.1.refseq_genomic.Symbol.tss.1500_500.fa:
	cp /home/reference_data/bioinfotree/task/gencode/dataset/hsapiens/42/$@ $@

MANE.GRCh38.v1.1.refseq_genomic.Symbol.tss.1500_500.bed:
	cp /home/reference_data/bioinfotree/task/gencode/dataset/hsapiens/42/$@ $@